### ISSUE TITLE
Create-SPSite feature from WhiteRabbit Slackbot

### ISSUE THREAD

**Issue by damsleth** [Puzzlepart/ASPC2017#17]
"@white-rabbit Create-SPSite [title],[description] " posts to a flow trigger, which adds a list item to our site provisioning directory

**Comment by tarjeieo** [comment]
You go boy!

**Comment by damsleth** [comment]
Just works. 
use @white-rabbit Create-SPSite [siteitle], [sitedescription].
Aliases are Request-SPSite.
Create-SPSite with no parameters outputs usage info.
